---
- name: "S4 Bucket {{ s4_destroy | ternary('Destroy', 'Deploy') }}"
  amazon.aws.s3_bucket:
    endpoint_url: "{{ s4_s4.endpointProtocol }}://{{ s4_s4.endpointAddress }}:{{ s4_s4.endpointPort }}"
    name: "{{ item }}"
    state: "{{ s4_destroy | ternary('absent', 'present') }}"
    access_key: "{{ s4_s4.endpointUser }}"
    secret_key: "{{ s4_s4.endpointPassword }}"
    region: us-east-1 # This will always be us-east-1, s4 only responds to requests for that region unless configured otherwise
  loop: "{{ s4_buckets }}"
